In [1]:
print("creating our own dataset")

creating our own dataset

In [2]:
import pandas as pd
dataset=pd.read_csv("C:\\Users\\shahz\\Downloads\\student_performance_noisy.csv")

In [3]:
df=pd.DataFrame(dataset)

In [4]:
df.columns

Index(['student_id', 'name', 'age', 'gender', 'study_hours', 'status'], dtype='object')

In [5]:
df

   student_id       name     age  gender study_hours status
0    STD-1001  Alexander      24    male         5.5   pass
1    STD-1002     Sophia      19  Female         3.0   pass
2    STD-1003      Liam       32    male         7.0   pass
3    STD-1004     Olivia  28 yrs  female         4.5   fail
4    STD-1005       Noah      45       M        -2.0   pass
..        ...        ...     ...     ...         ...    ...
75   STD-1076     Adrian      31    male         6.0   pass
76   STD-1077    Natalie      25  female         4.5   pass
77   STD-1078     Thomas      37    male         2.5   fail
78   STD-1079       Maya      20  female         8.0   pass
79   STD-1080      Isaac      34    male         6.5   pass

[80 rows x 6 columns]

In [6]:
df.describe()

       student_id       name age gender study_hours status
count          80         79  78     79          79     80
unique         80         79  31      6          17      6
top      STD-1001  Alexander  27   male         6.5   pass
freq            1          1   5     39           7     64

In [35]:
df.loc[(15),'status'] = 'pass'

In [43]:
z=df.drop(columns=['name'])

In [44]:
df=z

In [51]:
df=df.drop(columns=['student_id','age'])

In [61]:
df= df.drop(columns=['gender_female'])

In [62]:
df

   study_hours status  gender_male
0          5.5   pass         True
1          3.0   pass        False
2          7.0   pass         True
3          4.5   fail        False
4          5.0   pass         True
..         ...    ...          ...
75         6.0   pass         True
76         4.5   pass        False
77         2.5   fail         True
78         8.0   pass        False
79         6.5   pass         True

[80 rows x 3 columns]